package com.xworkz.collection.boot;

import java.util.Collection;
import java.util.LinkedList;

public class CollectionJustificationRunner {

	public static void main(String[] args) {
		String currancy1 = "Dollar";
		String currancy2 = "Ruppe";
		String currancy3 = "pounds";
		String currancy4 = "euro";
		String currancy5 = "Australian Dollar";
		String currancy6 = "Canidian Dollar";
		String currancy7 = "dinar";
		String currancy8 = "franc";
		String currancy9 = "rand";
		String currancy10 = "singapore dollar";
		String currancy11 = "ruble";
		String currancy12 = "peso";
		String currancy13 = "yen";
		String currancy14 = "barmudian Dollar";
		String currancy15 = "nepalese rupee";
		String currancy16 = "dram";
		String currancy17 = "real";
		String currancy18 = "shiling";
		String currancy19 = "krone";
		String currancy20 = "rial";
		String currancy21 = "Brunie Dollar";
		String currancy22 = "dong";
		String currancy23 = "cedi";
		String currancy24 = "taka";
		String currancy25 = "afgani";
		String currancy26 = "cubian peso";

		Collection<String> collection = new LinkedList<String>();
		System.out.println(collection.add(currancy26));
		System.out.println(collection.add(currancy25));
		System.out.println(collection.add(currancy24));
		System.out.println(collection.add(currancy23));
		System.out.println(collection.add(currancy22));
		System.out.println(collection.add(currancy21));
		System.out.println(collection.add(currancy20));
		System.out.println(collection.add(currancy19));
		System.out.println(collection.add(currancy18));
		System.out.println(collection.add(currancy17));
		System.out.println(collection.add(currancy16));
		System.out.println(collection.add(currancy15));
		System.out.println(collection.add(currancy14));
		System.out.println(collection.add(currancy13));
		System.out.println(collection.add(currancy12));
		System.out.println(collection.add(currancy11));
		System.out.println(collection.add(currancy10));
		System.out.println(collection.add(currancy9));
		System.out.println(collection.add(currancy8));
		System.out.println(collection.add(currancy7));
		System.out.println(collection.add(currancy6));
		System.out.println(collection.add(currancy5));
		System.out.println(collection.add(currancy4));
		System.out.println(collection.add(currancy3));
		System.out.println(collection.add(currancy2));
		System.out.println(collection.add(currancy1));
		collection.clear();
		System.out.println("total currancy numbers are =" + collection.size() + " currancies");
		collection.clear();
		System.out.println("~~~~~~~~~~~~~ended currancy~~~~~~~~~~~~~~~~~~");

		String Sweet1 = "jamun";
		String Sweet2 = "kesar pista";
		String Sweet3 = "laddu";
		String Sweet4 = "son papadi";
		String Sweet5 = "barfi";
		String Sweet6 = "kaju barfi";
		String Sweet7 = "kheer";
		String Sweet8 = "jalebi";
		String Sweet9 = "mysore pak";
		String Sweet10 = "rasagulla";
		String Sweet11 = "rasamalai";
		String Sweet12 = "kaju katli";
		String Sweet13 = "peda";
		String Sweet14 = "darawadh peda";

		Collection<String> collection2 = new LinkedList<String>();
		System.out.println(collection2.add(Sweet14));
		System.out.println(collection2.add(Sweet13));
		System.out.println(collection2.add(Sweet12));
		System.out.println(collection2.add(Sweet11));
		System.out.println(collection2.add(Sweet10));
		System.out.println(collection2.add(Sweet9));
		System.out.println(collection2.add(Sweet8));
		System.out.println(collection2.add(Sweet7));
		System.out.println(collection2.add(Sweet6));
		System.out.println(collection2.add(Sweet5));
		System.out.println(collection2.add(Sweet4));
		System.out.println(collection2.add(Sweet3));
		System.out.println(collection2.add(Sweet2));
		System.out.println(collection2.add(Sweet1));
		System.out.println("total sweets are " + collection2.size());
		collection2.clear();

		System.out.println("~~~~~~~~~~ended sweets~~~~~~~~~~~");

		String coupon1 = "kfc coupon";
		String coupon2 = "amazon coupon";
		String coupon3 = "flifkart";
		String coupon4 = "ecommerce";
		String coupon5 = "ebay";
		String coupon6 = "naika";
		String coupon7 = "purple";
		String coupon8 = "governmet";
		String coupon9 = "kia";
		String coupon10 = "maruti";
		String coupon11 = "tcs";
		String coupon12 = "yamaha coupons";

		Collection<String> collection3 = new LinkedList<String>();
		System.out.println(collection3.add(coupon12));
		System.out.println(collection3.add(coupon11));
		System.out.println(collection3.add(coupon10));
		System.out.println(collection3.add(coupon9));
		System.out.println(collection3.add(coupon8));
		System.out.println(collection3.add(coupon7));
		System.out.println(collection3.add(coupon6));
		System.out.println(collection3.add(coupon5));
		System.out.println(collection3.add(coupon4));
		System.out.println(collection3.add(coupon3));
		System.out.println(collection3.add(coupon2));
		System.out.println(collection3.add(coupon1));
		System.out.println("total coupons are =" + collection3.size());
		collection3.clear();

		System.out.println("~~~~~~~~~~~ended coupons~~~~~~~~~~~~");

		Collection<String> collection4 = new LinkedList<String>();

		String bike1 = "r15";
		String bike2 = "mt 200";
		String bike3 = "fz v2.0";
		String bike4 = "rx 100";
		String bike5 = "pulser";
		String bike6 = "classic 350";
		String bike7 = "meteor";
		String bike8 = "hunter 350";
		String bike9 = "pulser 220";
		String bike10 = "ninza";
		String bike11 = "bmw 650";
		String bike12 = "continental gt";
		String bike13 = "intereceptor";
		String bike14 = "access";
		String bike15 = "activa";
		String bike16 = "dio";
		String bike17 = "activa 125";
		String bike18 = "jupiter";

		System.out.println(collection4.add(bike18));
		System.out.println(collection4.add(bike17));
		System.out.println(collection4.add(bike16));
		System.out.println(collection4.add(bike15));
		System.out.println(collection4.add(bike14));
		System.out.println(collection4.add(bike13));
		System.out.println(collection4.add(bike12));
		System.out.println(collection4.add(bike11));
		System.out.println(collection4.add(bike10));
		System.out.println(collection4.add(bike9));
		System.out.println(collection4.add(bike8));
		System.out.println(collection4.add(bike7));
		System.out.println(collection4.add(bike6));
		System.out.println(collection4.add(bike5));
		System.out.println(collection4.add(bike4));
		System.out.println(collection4.add(bike3));
		System.out.println(collection4.add(bike2));
		System.out.println(collection4.add(bike1));
		System.out.println("total bikes are " + collection4.size());
		collection4.clear();

		System.out.println("~~~~~~~~~~~~ended bike~~~~~~~~~~~~~~~~");

		String mall1 = "orion";
		String mall2 = "mantri";
		String mall3 = "garuda";
		String mall4 = "forum";
		String mall5 = "gt world";
		String mall6 = "global malls";
		String mall7 = "nexus";
		String mall8 = "ub city mall";
		String mall9 = "orion";
		String mall10 = "elements mall";
		String mall11 = "binnypet eta";
		String mall12 = "capital mall";
		String mall13 = "dlf mall";
		String mall14 = "ambience mall";
		String mall15 = "WTP mall";
		String mall16 = "db city mall";
		String mall17 = "paragon mall";
		String mall18 = "grand vince mall";
		String mall19 = "inorbit mall";
		String mall20 = "acropolice";
		String mall21 = "chanakkya mall";
		String mall22 = "asian mall";
		String mall23 = "dubai mall";
		String mall24 = "edomortan mall";
		String mall25 = "resource mall";
		String mall26 = "central mall";
		String mall27 = "prussia";
		String mall28 = "utmal mall";
		String mall29 = "isthama mall";
		String mall30 = "iran mall";
		String mall31 = "sawgrass mall";
		String mall32 = "roosevelt mall";
		String mall33 = "south coast mall";
		String mall34 = "kingplace mall";
		String mall35 = "kibron mall";
		String mall36 = "limpa city mall";
		String mall37 = "kinto mall";
		String mall38 = "simom city mall";
		String mall39 = "pearls mall";
		String mall40 = "mall of america";

		Collection<String> collection5 = new LinkedList<String>();
		System.out.println(collection5.add(mall40));
		System.out.println(collection5.add(mall39));
		System.out.println(collection5.add(mall38));
		System.out.println(collection5.add(mall37));
		System.out.println(collection5.add(mall36));
		System.out.println(collection5.add(mall35));
		System.out.println(collection5.add(mall34));
		System.out.println(collection5.add(mall33));
		System.out.println(collection5.add(mall32));
		System.out.println(collection5.add(mall31));
		System.out.println(collection5.add(mall30));
		System.out.println(collection5.add(mall29));
		System.out.println(collection5.add(mall28));
		System.out.println(collection5.add(mall27));
		System.out.println(collection5.add(mall26));
		System.out.println(collection5.add(mall25));
		System.out.println(collection5.add(mall24));
		System.out.println(collection5.add(mall23));
		System.out.println(collection5.add(mall22));
		System.out.println(collection5.add(mall21));
		System.out.println(collection5.add(mall20));
		System.out.println(collection5.add(mall19));
		System.out.println(collection5.add(mall18));
		System.out.println(collection5.add(mall17));
		System.out.println(collection5.add(mall16));
		System.out.println(collection5.add(mall15));
		System.out.println(collection5.add(mall14));
		System.out.println(collection5.add(mall13));
		System.out.println(collection5.add(mall12));
		System.out.println(collection5.add(mall11));
		System.out.println(collection5.add(mall10));
		System.out.println(collection5.add(mall9));
		System.out.println(collection5.add(mall8));
		System.out.println(collection5.add(mall7));
		System.out.println(collection5.add(mall6));
		System.out.println(collection5.add(mall5));
		System.out.println(collection5.add(mall4));
		System.out.println(collection5.add(mall3));
		System.out.println(collection5.add(mall2));
		System.out.println(collection5.add(mall1));
		System.out.println("total malls are =" + collection5.size());
		collection5.clear();

		System.out.println("~~~~~~~~~~~~~~ended malls~~~~~~~~~~~~~~~~~~~");

	}

}
